const routes = {
  home: '/',
  minimal: '/minimal',
  retro: '/retro',
  swap: '/swap',
  analysis: '/analysis',
  stake: '/stake',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  farms: '/farms',
  farmsTwo: '/farms-2',
  createNft: '/create-nft',
  nftDetails: '/nft-details',
  search: '/search',
  notification: '/notification',
  vote: '/vote',
  proposals: '/proposals',
  createProposal: '/proposals/create',
  charts: '/charts',
  profile: '/profile',
  portfolio: '/profile?view=portfolio',
  history: '/profile?view=history',
  swap2: '/swap2',
  swap3: '/swap3',
};

export default routes;
